export const petTypes = [
  { value: "dog", label: "Dog" },
  { value: "cat", label: "Cat" },
  { value: "rabbit", label: "Rabbit" },
  { value: "fish", label: "Fish" },
]

export const breedsByType: Record<string, string[]> = {
  dog: [
    "Chihuahua",
    "Pomeranian",
    "Yorkshire Terrier",
    "Shih Tzu",
    "Maltese",
    "Toy Poodle",
    "Beagle",
    "Border Collie",
    "Boxer",
    "Bulldog",
    "Cocker Spaniel",
    "Dachshund",
    "German Shepherd",
    "Labrador Retriever",
    "Golden Retriever",
    "Rottweiler",
    "Great Dane",
    "Saint Bernard",
    "Mixed Breed",
  ],
  cat: [
    "Siamese",
    "Persian",
    "Maine Coon",
    "Ragdoll",
    "Bengal",
    "Sphynx",
    "British Shorthair",
    "Abyssinian",
    "Burmese",
    "Oriental",
    "Scottish Fold",
    "American Shorthair",
    "Domestic Shorthair",
    "Domestic Longhair",
    "Mixed Breed",
  ],
  rabbit: [
    "Holland Lop",
    "Mini Rex",
    "Netherland Dwarf",
    "Lionhead",
    "Dutch",
    "Flemish Giant",
    "English Angora",
    "New Zealand",
    "Mixed Breed",
  ],
  fish: ["Goldfish", "Betta", "Guppy", "Tetra", "Angelfish", "Discus", "Koi", "Molly", "Platy", "Swordtail"],
}

